# Form implementation generated from reading ui file 'test_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 20, 321, 231))
        self.stackedWidget.setStyleSheet("background-color: rgb(171, 235, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.connect_button = QtWidgets.QPushButton(parent=self.page)
        self.connect_button.setGeometry(QtCore.QRect(100, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUILatin 700")
        font.setPointSize(14)
        font.setBold(True)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.connect_button.clicked.connect(self.connection_page)

        self.create_account_button = QtWidgets.QPushButton(parent=self.page)
        self.create_account_button.setGeometry(QtCore.QRect(100, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUILatin 700")
        font.setPointSize(14)
        font.setBold(True)
        self.create_account_button.setFont(font)
        self.create_account_button.setObjectName("create_account_button")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(parent=self.page_2)
        self.label.setGeometry(QtCore.QRect(60, 40, 211, 51))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUILatin 700")
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(140, 110, 151, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(88, 189, 200);\n"
"color: rgb(238, 238, 238);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.page_2)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 41, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.page_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 150, 151, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgb(88, 189, 200);\n"
"color: rgb(238, 238, 238);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page_2)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 81, 20))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.connect_button.setText(_translate("Form", "Se connecter"))
        self.create_account_button.setText(_translate("Form", "Créer un compte"))
        self.label.setText(_translate("Form", "Connectez-vous"))
        self.label_2.setText(_translate("Form", "Email :"))
        self.label_3.setText(_translate("Form", "Mot de passe :"))

    def connection_page(self):
        self.stackedWidget.setCurrentIndex(1)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
